name: Deploy Vue App to S3 & Lambda Function to AWS

on:
  push:
    branches: [main]  # Triggered when pushing to main branch

jobs:
  # Deploy frontend to S3
  deploy-frontend-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build
        working-directory: ./frontend/arthritis
        run: |
          npm install
          npm run build  # Build Vue application

      - name: Deploy to S3 (version1)
        run: |
          # Upload to version2 folder
          aws s3 sync ./frontend/arthritis/dist s3://arthritisease.org/version2/ --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2
